#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

PLUGIN_ID="herdr-notifications"
GITHUB_REPO="wurthel/herdr-notifications"
MIN_HERDR="0.9.1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd || true)"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/herdr/plugins/$PLUGIN_ID"

fail() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }

# version_ge A B: true when version A >= B.
version_ge() { [[ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -n1)" == "$2" ]]; }

plugin_list() { herdr plugin list --json 2>/dev/null || true; }
plugin_installed() { plugin_list | grep -q "\"plugin_id\":\"$PLUGIN_ID\""; }

# plugin_is_local: true when the installed plugin is a linked checkout.
plugin_is_local() {
  if command -v jq >/dev/null 2>&1; then
    [[ "$(plugin_list | jq -r --arg id "$PLUGIN_ID" '.result.plugins[]? | select(.plugin_id == $id) | .source.kind')" == "local" ]]
  else
    herdr plugin list 2>/dev/null | grep -E "^- $PLUGIN_ID " | grep -q '\[local:'
  fi
}

# ask_default KEY "Prompt" DEFAULT [regex]: ask, fall back to DEFAULT, and
# repeat until the value matches regex.
ask_default() {
  local key="$1" prompt="$2" def="$3" re="${4:-.*}"
  while true; do
    ask "$key" "$prompt ${DIM}(default: $def)${RESET}"
    [[ -z "${!key}" ]] && printf -v "$key" '%s' "$def"
    [[ "${!key}" =~ ^${re}$ ]] && return
    warn "invalid value: ${!key}"
  done
}

# ── Mode ──────────────────────────────────────────────────────────────────
_clear
printf '\n%s%s  herdr-notifications%s\n\n' "$BOLD" "$BLUE" "$RESET"
say "Telegram notifications for herdr agents."
printf '\n'
step "1) Install or reconfigure"
step "2) Uninstall"
printf '\n'
MODE=""
while [[ "$MODE" != "1" && "$MODE" != "2" ]]; do
  printf '  %sChoose 1 or 2:%s ' "$BOLD" "$RESET"
  read -r MODE || exit 1
done

command -v herdr >/dev/null 2>&1 || fail "herdr is not installed or not on PATH. See https://herdr.dev"

if [[ "$MODE" == "1" ]]; then
  TOTAL_STAGES=5
  banner "Install herdr-notifications"

  # ── Stage 1 ─────────────────────────────────────────────────────────────
  stage "Check requirements"
  HERDR_VERSION="$(herdr --version 2>/dev/null | awk '{print $2}')"
  version_ge "$HERDR_VERSION" "$MIN_HERDR" || fail "herdr $HERDR_VERSION found; $MIN_HERDR or newer is required (run: herdr update)"
  say "${GREEN}✓${RESET} herdr $HERDR_VERSION"
  SERVER_STATUS="$(herdr status 2>/dev/null | awk '/^server:/{s=1} s && $1=="status:"{print $2; exit}')"
  [[ "$SERVER_STATUS" == "running" ]] || fail "the herdr server is not running. Start herdr, then re-run this script."
  SERVER_VERSION="$(herdr status 2>/dev/null | awk '/^server:/{s=1} s && $1=="version:"{print $2; exit}')"
  version_ge "$SERVER_VERSION" "$MIN_HERDR" || fail "the running herdr server is $SERVER_VERSION; restart it so it runs $MIN_HERDR or newer (herdr server stop, then start herdr)."
  say "${GREEN}✓${RESET} herdr server $SERVER_VERSION is running"
  command -v go >/dev/null 2>&1 || fail "Go is required to build the plugin. Install it from https://go.dev/dl/"
  say "${GREEN}✓${RESET} $(go version | awk '{print $3}')"
  pause "Press Enter to continue"

  # ── Stage 2 ─────────────────────────────────────────────────────────────
  stage "Install the plugin"
  LOCAL_AVAILABLE=false
  [[ -n "$SCRIPT_DIR" && -f "$SCRIPT_DIR/herdr-plugin.toml" ]] && LOCAL_AVAILABLE=true

  install_local() {
    say "Building in ${SCRIPT_DIR}…"
    (cd "$SCRIPT_DIR" && go build -trimpath -ldflags="-s -w" -o "$PLUGIN_ID" .) || fail "go build failed"
    if ! plugin_installed; then
      herdr plugin link "$SCRIPT_DIR" >/dev/null || fail "herdr plugin link failed"
    fi
  }
  install_github() {
    say "Installing $GITHUB_REPO from GitHub (herdr clones and builds it)…"
    herdr plugin install "$GITHUB_REPO" --yes >/dev/null || fail "herdr plugin install failed"
  }

  if plugin_installed; then
    if plugin_is_local; then
      say "Already installed as a linked checkout."
      if $LOCAL_AVAILABLE; then
        install_local
        say "${GREEN}✓${RESET} rebuilt the binary"
      fi
    else
      say "Already installed from GitHub."
      if confirm "Reinstall the latest version from GitHub?"; then
        herdr plugin uninstall "$PLUGIN_ID" >/dev/null || fail "herdr plugin uninstall failed"
        install_github
        say "${GREEN}✓${RESET} reinstalled"
      fi
    fi
  elif $LOCAL_AVAILABLE && confirm "Link this checkout ($SCRIPT_DIR)? No installs from GitHub instead"; then
    install_local
    say "${GREEN}✓${RESET} built and linked $SCRIPT_DIR"
  else
    install_github
    say "${GREEN}✓${RESET} installed from GitHub"
  fi
  plugin_installed || fail "$PLUGIN_ID is not in 'herdr plugin list' after installing"

  CONFIG_DIR="$(herdr plugin config-dir "$PLUGIN_ID")"
  mkdir -p "$CONFIG_DIR"
  chmod 700 "$CONFIG_DIR"
  ENV_FILE="$CONFIG_DIR/.env"
  note "config: $ENV_FILE"
  pause "Press Enter to continue"

  # ── Stage 3 ─────────────────────────────────────────────────────────────
  stage "Telegram bot"
  note "Bot token: @BotFather → /newbot (or /mybots → your bot → API Token)."
  note "Chat id: your numeric user id (e.g. from @userinfobot), a group id (negative) or @channel."
  note "Send your bot any message once, otherwise it cannot write to you."
  printf '\n'
  TELEGRAM_BOT_TOKEN=""
  while [[ -z "$TELEGRAM_BOT_TOKEN" ]]; do
    ask_secret TELEGRAM_BOT_TOKEN "Bot token:"
  done
  TELEGRAM_CHAT_ID=""
  while [[ -z "$TELEGRAM_CHAT_ID" ]]; do
    ask TELEGRAM_CHAT_ID "Chat id:"
  done

  # ── Stage 4 ─────────────────────────────────────────────────────────────
  stage "Notification settings"
  note "Press Enter to keep the value shown."
  printf '\n'
  ask_default NOTIFY_ON "Statuses that notify (idle, working, blocked, done):" "done,blocked" '[a-z]+(,[a-z]+)*'
  ask_default NOTIFY_IDLE_AFTER_WORKING "Treat working → idle as done, for agents finishing in a visible pane (1/0):" "1" '[01]'
  ask_default PANE_TAIL_LINES "Pane lines to send when no agent transcript is found (0-200):" "15" '[0-9]+'
  ask_default DEBOUNCE_SECONDS "Minimum seconds between repeated messages per pane:" "10" '[0-9]+'

  # ── Stage 5 ─────────────────────────────────────────────────────────────
  stage "Save and test"
  touch "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
  write_env TELEGRAM_CHAT_ID "$TELEGRAM_CHAT_ID"
  write_env NOTIFY_ON "$NOTIFY_ON"
  write_env NOTIFY_IDLE_AFTER_WORKING "$NOTIFY_IDLE_AFTER_WORKING"
  write_env PANE_TAIL_LINES "$PANE_TAIL_LINES"
  write_env DEBOUNCE_SECONDS "$DEBOUNCE_SECONDS"
  chmod 600 "$ENV_FILE"
  printf '\n'
  if confirm "Send a test message to Telegram now?"; then
    herdr plugin action invoke test --plugin "$PLUGIN_ID" >/dev/null 2>&1 || SKIPPED+=("test action could not be started")
    RESULT=""
    for _ in 1 2 3 4 5 6 7 8 9 10; do
      sleep 1
      RESULT="$(herdr plugin log list --plugin "$PLUGIN_ID" --limit 1 2>/dev/null || true)"
      [[ "$RESULT" == *'"status":"succeeded"'* || "$RESULT" == *'"status":"failed"'* ]] && break
    done
    if [[ "$RESULT" == *'"status":"succeeded"'* ]]; then
      say "${GREEN}✓${RESET} test message sent, check Telegram"
    else
      warn "the test did not succeed. Details: herdr plugin log list --plugin $PLUGIN_ID"
      SKIPPED+=("fix the Telegram settings, then re-run this script or: herdr plugin action invoke test --plugin $PLUGIN_ID")
    fi
    pause "Press Enter to finish"
  fi

  finish
  note "Mute/unmute any time: herdr plugin action invoke toggle --plugin $PLUGIN_ID"
  printf '\n'
else
  TOTAL_STAGES=2
  banner "Uninstall herdr-notifications"

  # ── Stage 1 ─────────────────────────────────────────────────────────────
  stage "Remove the plugin"
  CONFIG_DIR="$(herdr plugin config-dir "$PLUGIN_ID" 2>/dev/null || true)"
  if plugin_installed; then
    if plugin_is_local; then
      say "Installed as a linked checkout; unlinking leaves the checkout itself untouched."
      if confirm "Unlink $PLUGIN_ID from herdr?"; then
        herdr plugin unlink "$PLUGIN_ID" >/dev/null || fail "herdr plugin unlink failed"
        say "${GREEN}✓${RESET} unlinked"
      else
        SKIPPED+=("plugin still linked: herdr plugin unlink $PLUGIN_ID")
      fi
    else
      if confirm "Uninstall $PLUGIN_ID (removes herdr's managed checkout)?"; then
        herdr plugin uninstall "$PLUGIN_ID" >/dev/null || fail "herdr plugin uninstall failed"
        say "${GREEN}✓${RESET} uninstalled"
      else
        SKIPPED+=("plugin still installed: herdr plugin uninstall $PLUGIN_ID")
      fi
    fi
  else
    say "$PLUGIN_ID is not installed in herdr."
  fi
  pause "Press Enter to continue"

  # ── Stage 2 ─────────────────────────────────────────────────────────────
  stage "Remove settings and state"
  REMOVE=()
  [[ -n "$CONFIG_DIR" && -d "$CONFIG_DIR" ]] && REMOVE+=("$CONFIG_DIR")
  [[ -d "$STATE_DIR" ]] && REMOVE+=("$STATE_DIR")
  if (( ${#REMOVE[@]} )); then
    say "These hold your bot token and per-pane state:"
    for d in "${REMOVE[@]}"; do step "$d"; done
    printf '\n'
    if confirm "Delete them permanently?"; then
      rm -rf "${REMOVE[@]}"
      say "${GREEN}✓${RESET} deleted"
    else
      SKIPPED+=("settings kept in ${REMOVE[*]}")
    fi
  else
    say "No settings or state found."
  fi
  printf '\n'
  note "If this bot token is no longer needed, revoke it: @BotFather → /mybots → your bot → API Token → Revoke."
  pause "Press Enter to finish"

  _clear
  printf '\n%s%s  ✓ Uninstall complete%s\n' "$BOLD" "$GREEN" "$RESET"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
fi
