package transcript

import "testing"

func cUser(content any) obj {
	return obj{
		"type": "user", "isSidechain": false, "isMeta": false,
		"message": obj{"role": "user", "content": content},
	}
}

func cMeta(content any) obj {
	e := cUser(content)
	e["isMeta"] = true
	return e
}

func cSidechain(e obj) obj {
	e["isSidechain"] = true
	return e
}

func cAssistant(id string, blocks ...obj) obj {
	return obj{
		"type": "assistant", "isSidechain": false,
		"message": obj{"id": id, "role": "assistant", "content": blocks},
	}
}

func cText(s string) obj { return obj{"type": "text", "text": s} }

func cToolUse(id, name string, input obj) obj {
	return obj{"type": "tool_use", "id": id, "name": name, "input": input}
}

func cToolResult(id string) obj {
	return cUser([]obj{{"type": "tool_result", "tool_use_id": id, "content": "done"}})
}

var claudeNoise = []any{
	obj{"type": "attachment", "attachment": obj{"type": "file", "content": "x"}},
	obj{"type": "last-prompt", "lastPrompt": "ignored prompt"},
	obj{"type": "system", "subtype": "local_command", "content": "system text", "message": obj{"role": "user", "content": "noise"}},
	obj{"type": "file-history-snapshot", "snapshot": obj{}},
	obj{"type": "permission-mode", "mode": "plan"},
}

func TestClaudeBasicTurn(t *testing.T) {
	entries := append([]any{}, claudeNoise...)
	entries = append(entries,
		cUser("first prompt"),
		cAssistant("msg_1", cText("first answer")),
		cUser("second prompt"),
		cAssistant("msg_2", obj{"type": "thinking", "thinking": "hmm"}),
		cAssistant("msg_2", cText("Part one.")),
		cAssistant("msg_2", cToolUse("toolu_1", "Bash", obj{"command": "ls"})),
		cToolResult("toolu_1"),
		cAssistant("msg_3", cText("Final answer."), cText("More detail.")),
	)
	entries = append(entries, claudeNoise...)
	checkTurn(t, readFixture(t, "claude", entries...), Turn{
		Prompt: "second prompt",
		Output: "Final answer.\n\nMore detail.",
	})
}

func TestClaudeSkipsSyntheticPrompts(t *testing.T) {
	skipped := []any{
		cMeta("meta text"),
		cSidechain(cUser("subagent prompt")),
		cUser("<task-notification>\n<task-id>1</task-id>\n<status>completed</status>\n</task-notification>"),
		cUser("<local-command-caveat>Caveat: generated by local commands</local-command-caveat>\n<local-command-stdout>output</local-command-stdout>"),
		cUser("<system-reminder>remember this</system-reminder>"),
		cUser("[Request interrupted by user]"),
		cUser("[Request interrupted by user for tool use]"),
		cUser("   "),
		cUser([]obj{{"type": "image", "source": obj{"type": "base64"}}}),
	}
	for i, e := range skipped {
		entries := []any{cUser("real prompt"), cAssistant("msg_1", cText("answer")), e}
		checkTurn(t, readFixture(t, "claude", entries...), Turn{Prompt: "real prompt", Output: "answer"})
		if t.Failed() {
			t.Fatalf("entry %d was not skipped: %v", i, e)
		}
	}
}

func TestClaudeSidechainAssistantIgnored(t *testing.T) {
	checkTurn(t, readFixture(t, "claude",
		cUser("prompt"),
		cAssistant("msg_1", cText("main answer")),
		cSidechain(cAssistant("msg_2", cText("subagent answer"))),
		cSidechain(cAssistant("msg_3", cToolUse("toolu_9", "Bash", obj{"command": "rm -rf /"}))),
	), Turn{Prompt: "prompt", Output: "main answer"})
}

func TestClaudePromptForms(t *testing.T) {
	tests := []struct {
		name    string
		content any
		want    string
	}{
		{"plain string", "  fix the bug  ", "fix the bug"},
		{
			"slash command with args",
			"<command-name>/plan</command-name>\n<command-message>plan</command-message>\n<command-args>do X</command-args>",
			"/plan do X",
		},
		{
			"slash command without args",
			"<command-message>clear</command-message>\n<command-name>/clear</command-name>\n<command-args></command-args>",
			"/clear",
		},
		{"bash input", "<bash-input>ls -la</bash-input>", "! ls -la"},
		{
			"text blocks and image",
			[]obj{cText("look at this"), {"type": "image", "source": obj{"type": "base64", "data": "AAAA"}}, cText("and fix it")},
			"look at this\nand fix it",
		},
		{"multiline", "line one\nline two", "line one\nline two"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			checkTurn(t, readFixture(t, "claude", cUser(tt.content)), Turn{Prompt: tt.want})
		})
	}
}

func TestClaudeBashOutputAfterBashInputSkipped(t *testing.T) {
	checkTurn(t, readFixture(t, "claude",
		cUser("<bash-input>ls</bash-input>"),
		cUser("<bash-stdout>a\nb</bash-stdout><bash-stderr></bash-stderr>"),
	), Turn{Prompt: "! ls"})
}

func TestClaudeOutput(t *testing.T) {
	tests := []struct {
		name    string
		entries []any
		want    string
	}{
		{
			name: "split message joined",
			entries: []any{
				cAssistant("msg_1", cText("one")),
				cAssistant("msg_1", cToolUse("toolu_1", "Read", obj{"file_path": "/a"})),
				cToolResult("toolu_1"),
				cAssistant("msg_1", cText("two")),
			},
			want: "one\n\ntwo",
		},
		{
			name: "later message replaces earlier",
			entries: []any{
				cAssistant("msg_1", cText("old")),
				cAssistant("msg_2", cText("new")),
			},
			want: "new",
		},
		{
			name: "message without text keeps previous",
			entries: []any{
				cAssistant("msg_1", cText("kept")),
				cAssistant("msg_2", obj{"type": "thinking", "thinking": "..."}),
				cAssistant("msg_2", cText("   ")),
				cAssistant("msg_3", cToolUse("toolu_1", "Bash", obj{"command": "ls"})),
				cToolResult("toolu_1"),
			},
			want: "kept",
		},
		{
			name: "same id after another message is not appended",
			entries: []any{
				cAssistant("msg_1", cText("a")),
				cAssistant("msg_2", cText("b")),
				cAssistant("msg_1", cText("c")),
			},
			want: "c",
		},
		{
			name: "empty ids never join",
			entries: []any{
				cAssistant("", cText("a")),
				cAssistant("", cText("b")),
			},
			want: "b",
		},
		{
			name: "text trimmed",
			entries: []any{
				cAssistant("msg_1", cText("\n\n  answer \n")),
			},
			want: "answer",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			entries := append([]any{cUser("prompt")}, tt.entries...)
			checkTurn(t, readFixture(t, "claude", entries...), Turn{Prompt: "prompt", Output: tt.want})
		})
	}
}

func TestClaudeNewPromptResetsTurn(t *testing.T) {
	checkTurn(t, readFixture(t, "claude",
		cUser("first"),
		cAssistant("msg_1", cText("answer one")),
		cAssistant("msg_1", cToolUse("toolu_1", "Bash", obj{"command": "make"})),
		cUser("second"),
	), Turn{Prompt: "second"})
}

func TestClaudeSameIDNotJoinedAcrossPrompts(t *testing.T) {
	checkTurn(t, readFixture(t, "claude",
		cUser("first"),
		cAssistant("msg_1", cText("answer one")),
		cUser("second"),
		cAssistant("msg_1", cText("answer two")),
	), Turn{Prompt: "second", Output: "answer two"})
}

func TestClaudePending(t *testing.T) {
	tests := []struct {
		name  string
		tool  obj
		want  string
		reply bool
	}{
		{name: "answered", tool: cToolUse("toolu_1", "Bash", obj{"command": "ls"}), reply: true},
		{name: "bash", tool: cToolUse("toolu_1", "Bash", obj{"command": "  rm -rf build  ", "description": "clean"}), want: "Bash: rm -rf build"},
		{
			name: "ask user question",
			tool: cToolUse("toolu_1", "AskUserQuestion", obj{"questions": []obj{
				{"question": "Which database?", "options": []obj{{"label": "Postgres"}, {"label": "SQLite"}, {"description": "no label"}}},
				{"question": "Deploy now?", "options": []obj{{"label": "Yes"}}},
			}}),
			want: "Which database?\n• Postgres\n• SQLite\nDeploy now?\n• Yes",
		},
		{name: "ask user question without questions", tool: cToolUse("toolu_1", "AskUserQuestion", obj{}), want: "AskUserQuestion"},
		{name: "exit plan mode", tool: cToolUse("toolu_1", "ExitPlanMode", obj{"plan": "# Plan\n1. do it"}), want: "Plan approval"},
		{name: "unknown tool with file path", tool: cToolUse("toolu_1", "Edit", obj{"file_path": "/src/main.go", "old_string": "a"}), want: "Edit: /src/main.go"},
		{name: "unknown tool with url", tool: cToolUse("toolu_1", "WebFetch", obj{"url": "https://x.test"}), want: "WebFetch: https://x.test"},
		{name: "unknown tool with nothing", tool: cToolUse("toolu_1", "mcp__thing__do", obj{"n": 1}), want: "mcp__thing__do"},
		{name: "unknown tool with null input", tool: obj{"type": "tool_use", "id": "toolu_1", "name": "Mystery"}, want: "Mystery"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			entries := []any{
				cUser("prompt"),
				cAssistant("msg_1", cText("Let me check.")),
				cAssistant("msg_1", tt.tool),
			}
			if tt.reply {
				entries = append(entries, cToolResult("toolu_1"))
			}
			checkTurn(t, readFixture(t, "claude", entries...), Turn{Prompt: "prompt", Output: "Let me check.", Pending: tt.want})
		})
	}
}

func TestClaudePendingResultForOtherToolKeepsPending(t *testing.T) {
	checkTurn(t, readFixture(t, "claude",
		cUser("prompt"),
		cAssistant("msg_1", cToolUse("toolu_1", "Read", obj{"file_path": "/a"})),
		cToolResult("toolu_1"),
		cAssistant("msg_2", cToolUse("toolu_2", "Bash", obj{"command": "make deploy"})),
		cToolResult("toolu_other"),
	), Turn{Prompt: "prompt", Pending: "Bash: make deploy"})
}

func TestClaudeMetaToolResultClearsPending(t *testing.T) {
	result := cToolResult("toolu_1")
	result["isMeta"] = true
	checkTurn(t, readFixture(t, "claude",
		cUser("prompt"),
		cAssistant("msg_1", cToolUse("toolu_1", "Bash", obj{"command": "ls"})),
		result,
	), Turn{Prompt: "prompt"})
}

func TestClaudeMalformedLinesIgnored(t *testing.T) {
	checkTurn(t, readFixture(t, "claude",
		`{not json`,
		cUser("prompt"),
		`{"type":"user","message":{"content":`,
		`{"type":"assistant","message":{"id":"msg_x","content":"not an array"}}`,
		cAssistant("msg_1", cText("answer")),
		`garbage`,
		`[]`,
	), Turn{Prompt: "prompt", Output: "answer"})
}

func TestClaudeEmptyFile(t *testing.T) {
	if turn := readFixture(t, "claude"); !turn.Empty() {
		t.Errorf("expected empty turn, got %+v", turn)
	}
}

func TestClaudeParallelToolCalls(t *testing.T) {
	got := readFixture(t, "claude",
		map[string]any{"type": "user", "message": map[string]any{"role": "user", "content": "go"}},
		map[string]any{"type": "assistant", "message": map[string]any{"id": "m1", "role": "assistant", "content": []map[string]any{
			{"type": "tool_use", "id": "a", "name": "Bash", "input": map[string]any{"command": "first"}},
			{"type": "tool_use", "id": "b", "name": "Bash", "input": map[string]any{"command": "second"}},
		}}},
		map[string]any{"type": "user", "message": map[string]any{"role": "user", "content": []map[string]any{{"type": "tool_result", "tool_use_id": "b"}}}},
	)
	if got.Pending != "Bash: first" {
		t.Errorf("Pending = %q, want the still-unanswered first call", got.Pending)
	}
}
